server:
  port:8090
  name:ECOMMERCEV1
spring:
  data:
    mongodb:
      database: ECommerceV1Db
      host: localhost
      port: 27017
      auto-index-creation: true
  main:
    allow-bean-definition-overriding: true